# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  # config.vm.box = "centos/7"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    # vb.memory = "1024"
    vb.linked_clone = true
  end

  # Application server 1.
  config.vm.define "docker01" do |docker01|
    docker01.vm.hostname = "docker01"
    # docker01.vm.network "public_network"
    docker01.vm.network "public_network", ip: "192.168.2.12", netmask: "255.255.255.0"
  end

  # config.vm.provision "ansible_local" do |ansible|
  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yaml"
  end
end

# vim: ai et sw=2 ts=2 sts=2 nu
