#!/usr/bin/env bash

oc new-app --param="\
PIP_PROXY=${PIP_PROXY},\
SOURCE_REPOSITORY_URL=${SOURCE_REPOSITORY_URL},\
CONTEXT_DIR=${CONTEXT_DIR},\
APPLICATION_DOMAIN=${APPLICATION_DOMAIN},\
DEBUG=${DEBUG},\
DATABASE_USER=${DATABASE_USER},\
DATABASE_PASSWORD=${DATABASE_PASSWORD},\
DATABASE_NAME=${DATABASE_NAME},\
DISABLE_MIGRATE=${DISABLE_MIGRATE},\
DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY},\
DB_TABLE_NAME=${DB_TABLE_NAME},\
GIT_PROJECT_URL=${GIT_PROJECT_URL},\
DOCKERFILE_URL=${DOCKERFILE_URL}" -f \
 my_project/openshift/templates/django.yaml
