# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('tcp_address', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sid_nm', models.CharField(max_length=30)),
                ('full_nm', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=150)),
                ('work_phone_nbr_txt', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'custom_db_table_name',
                'ordering': ['full_nm'],
            },
        ),
    ]
